name: poi-push

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "apis/poi/**"

defaults:
  run:
    working-directory: ./apis/poi/web

jobs:
  build:
    name: poi-push-job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: azure/docker-login@v1
        with:
          login-server: openhack3j1036v7acr.azurecr.io
          username: ${{ secrets.ACR_USR }}
          password: ${{ secrets.ACR_PWD }}

      - run: |
          docker build . -t openhack3j1036v7acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}
          docker push openhack3j1036v7acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: "openhack3j1036v7poi"
          slot-name: "staging"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_POI_STA }}
          images: "openhack3j1036v7acr.azurecr.io/devopsoh/api-poi:${{ github.sha }}"

      - name: Healthcheck
        run: |
          chmod +x ./poi-health-check.sh
          ./poi-health-check.sh

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_DEPLOY_SP }}

      - name: Azure CLI script file
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az webapp deployment slot swap --name openhack3j1036v7poi --resource-group openhack3j1036v7rg --slot staging
