name: userjava-pr

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "apis/userjava/**"
jobs:
  build:
    name: userjava-pr-job
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '
