name: userjava-pr

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - "apis/userjava/**"

defaults:
  run:
    shell: bash
    working-directory: apis/userjava/

env: 
    JAVA_VERSION: '1.8'

jobs:
  build:
    name: userjava-pr-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    - name: Build using maven
      run: mvn clean install
    - name: Run tests
      run: mvn test
