name: userprofile-push

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "apis/userprofile/**"

defaults:
  run:
    working-directory: ./apis/userprofile

jobs:
  build:
    name: userprofile-push-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: openhack3j1036v7acr.azurecr.io
        username: ${{ secrets.ACR_USR }}
        password: ${{ secrets.ACR_PWD }}

    - run: |
        docker build . -t openhack3j1036v7acr.azurecr.io/devopsoh/api-userprofile:${{ github.sha }}
        docker push openhack3j1036v7acr.azurecr.io/devopsoh/api-userprofile:${{ github.sha }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: "openhack3j1036v7userprofile"
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_USERPROFILE }}
        images: "openhack3j1036v7acr.azurecr.io/devopsoh/api-userprofile:${{ github.sha }}"
